destinationHosts:
  destinationHost-0:
    userName: user
    hostName: localhost
    port: 22
    identityFile: ./id_rsa.pub
    jumphost:
      userName: user
      hostname: localhost
      port: 22
      identityFile: ./id_rsa.pub
      nextJumpHost:
        userName: user
        hostname: localhost
        port: 22
        identityFile: ./id_rsa.pub
  destinationHost-1:
    userName: user
    hostName: localhost
    port: 22
    identityFile: ./id_rsa.pub
    jumphost:
      userName: user
      hostname: localhost
      port: 22
      identityFile: ./id_rsa.pub
      nextJumpHost:
        userName: user
        hostname: localhost
        port: 22
        identityFile: ./id_rsa.pub